# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: MARuSS # The title of your site
author: "" # Will be shown in footer
email: contact email
description: > # Add a short description below:
  Musical Audio Repurposing using Source Separation
baseurl: "/maruss-website" # the name of your repository
url: "https://cvssp.github.io" # the base hostname & protocol for your site, e.g. http://example.com
query_by_this_bibtex_keyword: "maruss" # This can be empty, but you should use a keyword to separate your publications from others

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - jekyll/scholar
exclude:
  - Gemfile
  - Gemfile.lock
  - README
exclude: [vendor]
collections:
    publication_details:
        output: false
scholar:
    style: ./_bibliography/ieee-with-url.csl # Add any citation style file you like
    replace_strings: true
    bibliography: references.bib # The name if the default bib file (should live in ./_bibliography)
    bibliography_template: publications
    details_layout: publication.html
    details_link:   "{ Details }" # The text used to link to the details page
    details_dir: publications
    sort_by: year, month # Add any sorting preference here (see https://github.com/inukshuk/jekyll-scholar)
    order: descending
    group_order: descending
    repository: ./assets/pdfs # Location of your pdf files
